blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/r9yBeEWv
    about: Join our Discord for questions and community support
  - name: VRChat Group
    url: https://vrchat.com/home/group/grp_c2d5a5a6-2bf7-4eac-b92a-dd1f2363006b
    about: Join our VRChat group
